name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar testes simulados
        run: echo "Running tests"

      - name: Executar deploy simulado
        run: echo "Deploy"